chore: vercel deployment update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,27 +1,30 @@
-name: Test & Deploy
+name: Deploy to Vercel
 
 on:
   push:
     branches: [main]
 
 jobs:
-  test:
-    runs-on: ubuntu-latest
-    defaults:
-        run:
-            working-directory: ./backend
-
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '24'
-      - run: npm ci
-
   deploy:
     runs-on: ubuntu-latest
-    needs: test
     steps:
-      - name: Trigger Vercel
-        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
+      - uses: actions/checkout@v3
 
+      - name: Install Vercel CLI
+        run: npm install -g vercel
+
+      - name: Deploy to Vercel
+        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
+        env:
+          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
+          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
+      
+      - name: Trigger Vercel Deployment
+        run: |
+           response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }})
+           echo "Response code: $response"
+           if [ "$response" -ne 200 ] && [ "$response" -ne 201 ]; then
+            echo "❌ Deployment trigger failed with status $response"
+            exit 1
+           fi
+           echo "✅ Deployment triggered successfully."
