chore: uncomment url

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -117,21 +117,21 @@ jobs:
       #   curl --fail --retry 5 --retry-delay 10 \
       #     "${{ needs.deploy-backend-staging.outputs.staging_url }}/api/v1/books?page=1&perPage=8"
 
-    - name: Test All API Routes are Live
-      run: |
-        VITE_BACKEND_URL="https://book-reservation-system-backend.vercel.app/api/v1"
-        echo "Testing: $VITE_BACKEND_URL"
-        ROUTES=("books")
+    # - name: Test All API Routes are Live
+    #   run: |
+    #     VITE_BACKEND_URL="https://book-reservation-system-backend.vercel.app/api/v1"
+    #     echo "Testing: $VITE_BACKEND_URL"
+    #     ROUTES=("books")
 
-        for ROUTE in "${ROUTES[@]}"; do
-        STATUS=$(curl -s -o /dev/null -w "%{http_code}" --retry 3 "$VITE_BACKEND_URL/$ROUTE")
-          if [ "$STATUS" == "200" ] || [ "$STATUS" == "401" ] || [ "$STATUS" == "403" ]; then
-            echo "✅ /api/v1/$ROUTE returned $STATUS"
-          else
-            echo "❌ /api/v1/$ROUTE failed with status $STATUS"
-            exit 1
-          fi
-        done
+    #     for ROUTE in "${ROUTES[@]}"; do
+    #     STATUS=$(curl -s -o /dev/null -w "%{http_code}" --retry 3 "$VITE_BACKEND_URL/$ROUTE")
+    #       if [ "$STATUS" == "200" ] || [ "$STATUS" == "401" ] || [ "$STATUS" == "403" ]; then
+    #         echo "✅ /api/v1/$ROUTE returned $STATUS"
+    #       else
+    #         echo "❌ /api/v1/$ROUTE failed with status $STATUS"
+    #         exit 1
+    #       fi
+    #     done
 
    
         # backend deployment production
